{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "ytempest-asm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "g6jlam5fybbbni77k2b6wgbcpu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 6625,
          "sha512": "11cda224428c3e41a5bbd2bb52432004f92ac2c95d0178013da3d9ee68ab701214db49db87265445c3d8911930d95fc2be3d359ed4c7b2e183163e0e1262b284",
          "sha256": "d07bc11bcc2ec1d2e80fb5bdbe449e9c8f407ac2f42b33a635e2d013323db49e",
          "sha1": "e43b379c5f571d2bf12854b61feff64d079fadf4",
          "md5": "e91d498a6c2f98834b2ae19ac883f9fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 6625,
          "sha512": "11cda224428c3e41a5bbd2bb52432004f92ac2c95d0178013da3d9ee68ab701214db49db87265445c3d8911930d95fc2be3d359ed4c7b2e183163e0e1262b284",
          "sha256": "d07bc11bcc2ec1d2e80fb5bdbe449e9c8f407ac2f42b33a635e2d013323db49e",
          "sha1": "e43b379c5f571d2bf12854b61feff64d079fadf4",
          "md5": "e91d498a6c2f98834b2ae19ac883f9fb"
        }
      ]
    }
  ]
}
