{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "ytempest-asm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "dww42jhpxzcjznkwtlfix4lrd4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 6625,
          "sha512": "285b6e3ebfbaf956d314b31b2f4ed2e624b019649caab5e0abdc016882aedc62f40aed274fcdf99496ab19109e31d410aafb61fad19c648f6edeaf57a89c1ef4",
          "sha256": "c2213bb5a16765db77f242bbc56030ac5dc1d7a5dc4d4fa74a1ea13f0d93cc06",
          "sha1": "9d691ec4611533de71e7f15adfdbf38a1a9fe111",
          "md5": "df04c52b88eb86c92de320822c775d6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 6625,
          "sha512": "285b6e3ebfbaf956d314b31b2f4ed2e624b019649caab5e0abdc016882aedc62f40aed274fcdf99496ab19109e31d410aafb61fad19c648f6edeaf57a89c1ef4",
          "sha256": "c2213bb5a16765db77f242bbc56030ac5dc1d7a5dc4d4fa74a1ea13f0d93cc06",
          "sha1": "9d691ec4611533de71e7f15adfdbf38a1a9fe111",
          "md5": "df04c52b88eb86c92de320822c775d6a"
        }
      ]
    }
  ]
}
