{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "ytempest-asm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "5tpqzv4ecveshj7zekwmyle5hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 15302,
          "sha512": "4d925d628a97d8de0b13c4ebdd1d1c9d83a6e7765547552657ca7be7f15043ffffbbaf83f9b0d7baa51e3cf7bc487c302bf5da58e09ecf23efb4e048f668c873",
          "sha256": "81aa648151910f43a88e5584640c065cc8e48e4810d4618fbd5345006b84e77c",
          "sha1": "36549c9e7ddf9e1340985ea0d0aa4d743de51990",
          "md5": "8a0defa823010b677ba645b700e61e96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "ytempest-asm-1.0.0.jar",
          "url": "ytempest-asm-1.0.0.jar",
          "size": 15302,
          "sha512": "4d925d628a97d8de0b13c4ebdd1d1c9d83a6e7765547552657ca7be7f15043ffffbbaf83f9b0d7baa51e3cf7bc487c302bf5da58e09ecf23efb4e048f668c873",
          "sha256": "81aa648151910f43a88e5584640c065cc8e48e4810d4618fbd5345006b84e77c",
          "sha1": "36549c9e7ddf9e1340985ea0d0aa4d743de51990",
          "md5": "8a0defa823010b677ba645b700e61e96"
        }
      ]
    }
  ]
}
