{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "dynamic-so",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "qs3iywigtfdctjuwjgvxfggnae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 51486,
          "sha512": "3b2e8d2582de7c3f43bb656ba520354018a5797508c9ac705f62bf476f6c40fe8cf49d3dc3ce9b4b2eba5bd456a36a5f99d636d9f893b84baad3dc4a6248dda9",
          "sha256": "b0a1b28e28b7ab30dbac67d4eb9232a7593238e7919e6731bc105584430f57c1",
          "sha1": "33999bd05ca26072df0467852154a1ba6a98e7de",
          "md5": "ee8dfb38b22d798de9cd55aa21c0ccf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-android"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.json",
          "module": "org.json",
          "version": {
            "requires": "chargebee-1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 51486,
          "sha512": "3b2e8d2582de7c3f43bb656ba520354018a5797508c9ac705f62bf476f6c40fe8cf49d3dc3ce9b4b2eba5bd456a36a5f99d636d9f893b84baad3dc4a6248dda9",
          "sha256": "b0a1b28e28b7ab30dbac67d4eb9232a7593238e7919e6731bc105584430f57c1",
          "sha1": "33999bd05ca26072df0467852154a1ba6a98e7de",
          "md5": "ee8dfb38b22d798de9cd55aa21c0ccf0"
        }
      ]
    }
  ]
}
