{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "dynamic-so",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "jkty4pmccfhzbbgq76go6gwyzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 52145,
          "sha512": "b247dbd78e3b496c2fc0fc331b6cb686d12a5c03ffe4927f26e60dabdc5507fe03131e5b57582f93b3a299f6cce5e26c1ec1538fe35e7988f82d4aec74bfb579",
          "sha256": "8d975e1c22c70fdab3abe82531723db2adb952a9896796c93cb2a4dc49f23f46",
          "sha1": "377b232c12bb663bc25e638ea84bb840ab056ee5",
          "md5": "2808e09f4754c9c210bd67514f005c6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-android"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.json",
          "module": "org.json",
          "version": {
            "requires": "chargebee-1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 52145,
          "sha512": "b247dbd78e3b496c2fc0fc331b6cb686d12a5c03ffe4927f26e60dabdc5507fe03131e5b57582f93b3a299f6cce5e26c1ec1538fe35e7988f82d4aec74bfb579",
          "sha256": "8d975e1c22c70fdab3abe82531723db2adb952a9896796c93cb2a4dc49f23f46",
          "sha1": "377b232c12bb663bc25e638ea84bb840ab056ee5",
          "md5": "2808e09f4754c9c210bd67514f005c6c"
        }
      ]
    }
  ]
}
