plugins {
    id 'com.android.application'
    id 'org.greenrobot.greendao'
    id 'kotlin-android'
    id 'kotlin-kapt'// kapt 插件

//    id 'dynamic-so'
    id 'ytempest-asm'
}

android {
    compileSdkVersion versions.compileSdk

    defaultConfig {
        applicationId "com.ytempest.wanandroid"
        minSdkVersion versions.minSdk
        targetSdkVersion versions.targetSdk
        versionCode versions.versionCode
        versionName versions.versionName
        multiDexEnabled true

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    signingConfigs {
        release {
            storeFile file("wan.jks")
            storePassword "wanandroid"
            keyAlias "wan"
            keyPassword "wanandroid"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    viewBinding {
        enabled = true
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['jni']
            aidl.srcDirs = ['src']
        }
    }
}

greendao {
    schemaVersion 1 //当前数据库版本
}

dependencies {
    implementation fileTree(include: ['*.aar'], dir: 'aar')
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    testImplementationDeps.each { k, v -> testImplementation v }
    androidTestImplementationDeps.each { k, v -> androidTestImplementation v }

    implementationDeps.each { k, v -> implementation v }
    annotationProcessorDeps.each { k, v -> kapt v }

    implementation project(path: ':framework')
}