{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ytempest.plugin",
    "module": "dynamic-so",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "asvmyiq4qre3roa2rryvibcw7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 61374,
          "sha512": "beaa2815fde13d764427b549f021389829533fade7fae54434235d77c90a9459b8cd35f32aa93b98d64b52f568c8c3452294ad3e010a74465d9e30d5061168c0",
          "sha256": "6fbd19e29977bf4f84541faf3bdec08cbdecf544249b4ac8670a3ff271d37807",
          "sha1": "b2deaa7d2579d64868230ce539b8c076d1a7d380",
          "md5": "5ad17f329f86a47fea70bd23835d2c28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.0.1-android"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.json",
          "module": "org.json",
          "version": {
            "requires": "chargebee-1.0"
          }
        }
      ],
      "files": [
        {
          "name": "dynamic-so-1.0.0.jar",
          "url": "dynamic-so-1.0.0.jar",
          "size": 61374,
          "sha512": "beaa2815fde13d764427b549f021389829533fade7fae54434235d77c90a9459b8cd35f32aa93b98d64b52f568c8c3452294ad3e010a74465d9e30d5061168c0",
          "sha256": "6fbd19e29977bf4f84541faf3bdec08cbdecf544249b4ac8670a3ff271d37807",
          "sha1": "b2deaa7d2579d64868230ce539b8c076d1a7d380",
          "md5": "5ad17f329f86a47fea70bd23835d2c28"
        }
      ]
    }
  ]
}
